# Generated by Django 4.2.2 on 2023-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitefix',
            name='status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Not Fixed', 'Not Fixed')], default='Not Fixed', max_length=20),
        ),
    ]
