# Generated by Django 4.2.2 on 2024-01-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_fixes_app', '0002_websitefix_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteFix',
        ),
        migrations.DeleteModel(
            name='WebsiteFixTag',
        ),
    ]
