# Generated by Django 4.2.2 on 2023-09-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_answer_created_by_question_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
