# Generated by Django 4.2.2 on 2023-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_remove_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
