# Generated by Django 4.2.2 on 2023-09-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_question_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sequence',
        ),
    ]
