# Generated by Django 4.2.2 on 2023-10-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rescuetime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "productive_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "distracting_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
