# Generated by Django 4.2.2 on 2023-06-22 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
